### ISSUE TITLE
implement smart search and destroy

### ISSUE THREAD

**Issue by JonathanStarup** [mlutze/flixball#54]
Related to #4.

algorithm
* go to the nearest tile where another player can be seen (with the new predicate on goTo)
* shoot

**Comment by mlutze** [comment]
Can we also take into account the time to turn? For example
```
 aa
  aa
   aa
    aa
```
```
 bbbb
    b
    b
    b
```

Those paths travel the same distance but the diagonal one takes twice as long because of all the turns.

**Comment by JonathanStarup** [comment]
Yea I thought about that too. The graph you're really interested in when you're a robot in this universe is the grid with a separate distance to each rotation. Then you also don't have to do cumbersome `Coordinates -> actualMoves` transformations and the predicate on the graph destination can be more meaningful. I'll try to add this at some point, but claim no ownership if you feel inspired 😁
