### ISSUE TITLE
refactor: separate GameState and the AIs

### ISSUE THREAD

**Issue by JonathanStarup** [mlutze/flixball#76]
Based on the discussion in #40
* Have a new opaque type `AiInfo` that is given to the AI function
* Define `getPlayerMap` and `getTileMap` on this type; this allows us to change the internals without changing the AIs
* This `AiInfo` type will hold a `Board` and a `Map[PlayerId, Position]` but can be changed
This means that we are flexible in representation, stable in AI implementations, and GameState is exclusively there for game simulation

agree with this @mlutze? (Very open for a better name than `AiInfo`)

**Comment by mlutze** [comment]
This all looks reasonable to me. `getTileMap` will return a `Board` or are we separating those as well?

**Comment by JonathanStarup** [comment]
it will return `Map[Coordinate, Tile]`. Id like the ai accessible data do be data oblivious

**Comment by mlutze** [comment]
Ok. But we probably want to return the dimensions of the board as well :)

**Comment by mlutze** [comment]
> Yeah, good point. But we can add `get dimensions` on the `AiInfo` type. I think this type of scenario (oops, we forgot some information) is the reason it's a good change. Just add another function without committing to the data stored.

Yes, I agree.

> Sometimes it feels like the more theory I learn, the worse I become at programming. Instead of just coding, I'm wondering about whatever this is like a co-datatype smile (I guess with co-data, you're still committed to what kind of observations your data has?)

Reminds me of that data-codata language we saw in Tubingen

**Comment by JonathanStarup** [comment]
@mlutze what do you think of this signature for the ais?
```scala
/// given a seed and a player id, the strategy determines a starting
/// state and a move logic.
pub type alias Strategy = Int32 -> PlayerId -> (AiState, MoveLogic)

pub type alias MoveLogic = (AiInfo, AiState) -> (Move, AiState)
```

**Comment by mlutze** [comment]
Yes, this looks really good. I was previously thinking of giving the initial state just as an `AiState.Value(x)` but the seed -> state function is much cleaner

**Comment by mlutze** [comment]
I think the second option is preferable, for the reason you stated

**Comment by JonathanStarup** [comment]
> I think the second option is preferable, for the reason you stated

I've implemented this version but found one caveat: the move logic now does not know about the seed which also means that it does not know about the initial state. This means that it cannot go back to the initial state on state parsing error. is this bad? maybe its fine. It can just reset to its initial state function with state 0 ex.

**Comment by mlutze** [comment]
> > I think the second option is preferable, for the reason you stated
> 
> I've implemented this version but found one caveat: the move logic now does not know about the seed which also means that it does not know about the initial state. This means that it cannot go back to the initial state on state parsing error. is this bad? maybe its fine. It can just reset to its initial state function with state 0 ex.

I think it's ok. If it's a parsing error then it's theoretically the bot's own fault for putting it there so it must deal with the consequences:)
